# Generated by Django 6.0.3 on 2026-03-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_user_phone_number_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
