# Generated by Django 6.0.3 on 2026-03-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_dispute_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='auctions.auction'),
        ),
    ]
