# Generated by Django 6.0.5 on 2026-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_buy_now_price_auction_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Only visible to Gold/Platinum members'),
        ),
        migrations.AddField(
            model_name='auction',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Upload .glb or .gltf files for 3D viewing', null=True, upload_to='3d_models/'),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
